apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helloworld-rules
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: helloworld-v1.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: helloworld-v1
            port:
              number: 80
